//
//  ViewCountMacro
//  movikr
//
//  Created by Mapollo27 on 15/5/29.
//  Copyright (c) 2015年 movikr. All rights reserved.
//

//2.	按钮被点击次数，随便逛逛页：
#define cinemaSearchBtn               @"cinemaSearchBtn"//@"随便逛逛页_点击搜索按钮"
#define cinemaSearchChangeCityBtn     @"cinemaSearchChangeCityBtn"//@"随便逛逛页_点击修改城市按钮"
#define cinemaSearchLoginBtn          @"cinemaSearchLoginBtn"//@"随便逛逛页_点击登录按钮"

//3.	按钮被点击次数，修改城市页：
#define modifyCityViewSearchBtn               @"modifyCityViewSearchBtn" //@"修改城市页_点击搜索栏"
#define modifyCityViewLocationBtn             @"modifyCityViewLocationBtn" //@"修改城市页_点击定位失败按钮"

//4.	按钮被点击次数，登录页：
#define loginViewbtn1               @"loginViewbtn1" //@"登录页_点击登录按钮"
#define loginViewbtn2               @"loginViewbtn2" //@"登录页_点击忘记密码按钮"
#define loginViewbtn3               @"loginViewbtn3" //@"登录页_点击使用协议按钮"
#define loginViewbtn4               @"loginViewbtn4" //@"登录页_点击第三方微信登录按钮"
#define loginViewbtn5               @"loginViewbtn5" //@"登录页_点击第三方QQ登录按钮"
#define loginViewbtn6               @"loginViewbtn6" //@"登录页_点击第三方微博登录按钮"
#define loginViewbtn7               @"loginViewbtn7" //@"登录页_点击立即注册按钮"
#define loginViewbtn8               @"loginViewbtn8" //@"登录页_点击关闭按钮"
//5.	按钮被点击次数，注册页：
#define registerViewbtn1               @"registerViewbtn1" //@"注册页_点击注册按钮"
#define registerViewbtn2               @"registerViewbtn2" //@"注册页_点击获取验证码按钮"
#define registerViewbtn3               @"registerViewbtn3" //@"注册页_点击使用协议按钮"
#define registerViewbtn4               @"registerViewbtn4" //@"注册页_点击第三方微信登录按钮"
#define registerViewbtn5               @"registerViewbtn5" //@"注册页_点击第三方QQ登录按钮"
#define registerViewbtn6               @"registerViewbtn6" //@"注册页_点击第三方微博登录按钮"
#define registerViewbtn7               @"registerViewbtn7" //@"注册页_点击返回按钮"
//6.	按钮被点击次数，忘记密码页：
#define findPwdViewbtn1               @"findPwdViewbtn1" //@"忘记密码页_点击登录按钮"
#define findPwdViewbtn2               @"findPwdViewbtn2" //@"忘记密码页_点击获取验证码按钮"
#define findPwdViewbtn3               @"findPwdViewbtn3" //@"忘记密码页_点击关闭按钮"
//7.	按钮被点击次数，影院首页：
#define mainViewbtn1               @"mainViewbtn1" //@"首页_点击二维码扫描按钮"
#define mainViewbtn2               @"mainViewbtn2" //@"首页_二维码扫描页_点击相册按钮"
#define mainViewbtn3               @"mainViewbtn3" //@"首页_二维码扫描页_点击开启闪光灯按钮"
#define mainViewbtn4               @"mainViewbtn4" //@"首页_二维码扫描页_点击关闭闪光灯按钮"
#define mainViewbtn5               @"mainViewbtn5" //@"首页_二维码扫描页_点击返回按钮"
#define mainViewbtn6               @"mainViewbtn6" //@"首页_点击全局搜索按钮"
#define mainViewbtn7               @"mainViewbtn7" //@"首页_全局搜索页_点击搜索栏"
#define mainViewbtn8               @"mainViewbtn8" //@"首页_全局搜索页_点击影院搜索结果"
#define mainViewbtn9               @"mainViewbtn9" //@"首页_全局搜索页_点击影片搜索结果"
#define mainViewbtn10              @"mainViewbtn10" //@"首页_全局搜索页_影片搜索结果_点击购票按钮"
#define mainViewbtn11              @"mainViewbtn11" //@"首页_全局搜索页_点击用户搜索结果"
#define mainViewbtn12              @"mainViewbtn12" //@"首页_全局搜索页_点击城市按钮"
#define mainViewbtn13              @"mainViewbtn13" //@"首页_全局搜索页_点击搜索历史"
#define mainViewbtn14              @"mainViewbtn14" //@"首页_全局搜索页_点击清空按钮"
#define mainViewbtn15              @"mainViewbtn15" //@"首页_全局搜索页_点击返回按钮"
#define mainViewbtn16              @"mainViewbtn16" //@"首页_点击影院详情页"
#define mainViewbtn17              @"mainViewbtn17" //@"首页_影院详情页_点击影院地址"
#define mainViewbtn18              @"mainViewbtn18" //@"首页_影院详情页_点击影院电话"
#define mainViewbtn19              @"mainViewbtn19" //@"首页_影院详情页_点击影院公告按钮"
#define mainViewbtn20              @"mainViewbtn20" //@"首页_影院详情页_点击切换影院按钮"
#define mainViewbtn21              @"mainViewbtn21" //@"首页_影院详情页_点击返回按钮"

//8.	按钮被点击次数，影院首页_看电影：
#define mainViewbtn22               @"mainViewbtn22" //@"首页_点击看电影"
#define mainViewbtn23               @"mainViewbtn23" //@"首页_点击购票按钮_购票页"
#define mainViewbtn24               @"mainViewbtn24" //@"首页_点击购票按钮_购票页_点击场次日期"
#define mainViewbtn25               @"mainViewbtn25" //@"首页_点击购票按钮_购票页_点击场次"
#define mainViewbtn26               @"mainViewbtn26" //@"首页_点击购票按钮_购票页_选座页"
#define mainViewbtn27               @"mainViewbtn27" //@"首页_点击购票按钮_购票页_选座页_点击座位"
#define mainViewbtn28               @"mainViewbtn28" //@"首页_点击购票按钮_购票页_选座页_点击更换场次"
#define mainViewbtn29               @"mainViewbtn29" //@"首页_点击购票按钮_购票页_选座页_点击更换场次_点击场次日期"
#define mainViewbtn30               @"mainViewbtn30" //@"首页_点击购票按钮_购票页_选座页_点击更换场次_点击场次"
#define mainViewbtn31               @"mainViewbtn31" //@"首页_点击购票按钮_购票页_选座页_点击选好了按钮"
#define mainViewbtn32               @"mainViewbtn32" //@"首页_点击购票按钮_购票页_选座页_点击返回按钮"
#define mainViewbtn33               @"mainViewbtn33" //@"首页_点击购票按钮_购票页_卖品选择页_点击卖品数量(加)"
#define mainViewbtn34               @"mainViewbtn34" //@"首页_点击购票按钮_购票页_卖品选择页_点击卖品数量(减)"
#define mainViewbtn35               @"mainViewbtn35" //@"首页_点击购票按钮_购票页_卖品选择页_点击不需要卖品按钮"
#define mainViewbtn36               @"mainViewbtn36" //@"首页_点击购票按钮_购票页_卖品选择页_点击选好了按钮"
#define mainViewbtn37               @"mainViewbtn37" //@"首页_点击购票按钮_购票页_卖品选择页_点击返回按钮"
#define mainViewbtn38               @"mainViewbtn38" //@"首页_点击购票按钮_购票页_订单确认页_点击权益优惠"
#define mainViewbtn39               @"mainViewbtn39" //@"首页_点击购票按钮_购票页_订单确认页_点击权益优惠_勾选优惠"
#define mainViewbtn40               @"mainViewbtn40" //@"首页_点击购票按钮_购票页_订单确认页_点击权益优惠_点击优惠数量(加)"
#define mainViewbtn41               @"mainViewbtn41" //@"首页_点击购票按钮_购票页_订单确认页_点击权益优惠_点击优惠数量(减)"
#define mainViewbtn42               @"mainViewbtn42" //@"首页_点击购票按钮_购票页_订单确认页_点击权益优惠_点击选好了按钮"
#define mainViewbtn43               @"mainViewbtn43" //@"首页_点击购票按钮_购票页_订单确认页_点击手机号栏"
#define mainViewbtn44               @"mainViewbtn44" //@"首页_点击购票按钮_购票页_订单确认页_点击查看明细按钮"
#define mainViewbtn45               @"mainViewbtn45" //@"首页_点击购票按钮_购票页_订单确认页_点击确认订单按钮"
#define mainViewbtn46               @"mainViewbtn46" //@"首页_点击购票按钮_购票页_订单确认页_点击返回按钮"
#define mainViewbtn47               @"mainViewbtn47" //@"首页_点击购票按钮_购票页_支付选择页_点击微信支付"
#define mainViewbtn48               @"mainViewbtn48" //@"首页_点击购票按钮_购票页_支付选择页_点击支付宝支付"
#define mainViewbtn49               @"mainViewbtn49" //@"首页_点击购票按钮_购票页_支付选择页_点击Apple Pay支付"
#define mainViewbtn50               @"mainViewbtn50" //@"首页_点击购票按钮_购票页_支付选择页_点击确认支付按钮"
#define mainViewbtn51               @"mainViewbtn51" //@"首页_点击购票按钮_购票页_支付选择页_点击返回按钮"

//购票成功页
#define mainViewbtn52               @"mainViewbtn52" //@"首页_点击购票按钮_购票页_购票成功页_点击首页按钮"
#define mainViewbtn53               @"mainViewbtn53" //@"首页_点击购票按钮_购票页_购票成功页_点击查看订单按钮"
#define mainViewbtn54               @"mainViewbtn54" //@"首页_点击购票按钮_购票页_购票成功页_点击立即领取按钮"
#define mainViewbtn55               @"mainViewbtn55" //@"首页_点击购票按钮_购票页_购票成功页_获得奖励页"
#define mainViewbtn56               @"mainViewbtn56" //@"首页_点击购票按钮_购票页_购票成功页_获得奖励页_点击知道了按钮"
#define mainViewbtn57               @"mainViewbtn57" //@"首页_点击购票按钮_购票页_购票成功页_获得奖励页_点击关闭按钮"
#define mainViewbtn58               @"mainViewbtn58" //@"首页_点击购票按钮_购票页_购票成功页_出票失败页"
#define mainViewbtn59               @"mainViewbtn59" //@"首页_点击购票按钮_购票页_购票成功页_出票失败页_点击关闭按钮"

//9.	按钮被点击次数，影院首页_捡便宜：
#define mainViewbtn60               @"mainViewbtn60" //@"首页_点击捡便宜"
#define mainViewbtn61               @"mainViewbtn61" //@"首页_点击免费开通按钮"
#define mainViewbtn62               @"mainViewbtn62" //@"首页_点击免费开通按钮_登录页"
#define mainViewbtn63               @"mainViewbtn63" //@"首页_点击免费开通按钮_点击登录按钮"//
#define mainViewbtn64               @"mainViewbtn64" //@"首页_点击免费开通按钮_普通会员详情页"
#define mainViewbtn65               @"mainViewbtn65" //@"首页_点击免费开通按钮_普通会员详情页_点击免费开通按钮"
#define mainViewbtn66               @"mainViewbtn66" //@"首页_点击免费开通按钮_普通会员详情页_点击关闭按钮"//
#define mainViewbtn67               @"mainViewbtn67" //@"首页_点击去看看按钮"
#define mainViewbtn68               @"mainViewbtn68" //@"首页_点击去看看按钮_尊享会员详情"
#define mainViewbtn69               @"mainViewbtn69" //@"首页_点击去看看按钮_尊享会员详情页_点击开通按钮"
#define mainViewbtn70               @"mainViewbtn70" //@"首页_点击去看看按钮_尊享会员详情页_点击开通按钮_尊享卡购买页"
#define mainViewbtn71               @"mainViewbtn71" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_点击价格按钮"
#define mainViewbtn72               @"mainViewbtn72" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_点击返回按钮"//
#define mainViewbtn73               @"mainViewbtn73" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_点击价格按钮_订单确认页"
#define mainViewbtn74               @"mainViewbtn74" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_订单确认页_点击权益优惠页"
#define mainViewbtn75               @"mainViewbtn75" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_订单确认页_权益优惠页_点击优惠数量(加)"
#define mainViewbtn76               @"mainViewbtn76" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_订单确认页_权益优惠页_点击优惠数量(减)"
#define mainViewbtn77               @"mainViewbtn77" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_订单确认页_权益优惠页_点击实付金额按钮"
#define mainViewbtn78               @"mainViewbtn78" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_订单确认页_点击手机号栏"
#define mainViewbtn79               @"mainViewbtn79" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_订单确认页_点击查看明细按钮"
#define mainViewbtn80               @"mainViewbtn80" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_订单确认页_点击确认订单按钮"
#define mainViewbtn81               @"mainViewbtn81" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_订单确认页_点击返回按钮"//
#define mainViewbtn82               @"mainViewbtn82" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_支付选择页_点击微信支付"//
#define mainViewbtn83               @"mainViewbtn83" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_支付选择页_点击支付宝支付"//
#define mainViewbtn84               @"mainViewbtn84" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_支付选择页_点击Apple Pay支付"//
#define mainViewbtn85               @"mainViewbtn85" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_支付选择页_点击确认支付按钮"//
#define mainViewbtn86               @"mainViewbtn86" //@"首页_点击去看看按钮_尊享会员详情页_尊享卡购买页_支付选择页_点击返回按钮"//
#define mainViewbtn87               @"mainViewbtn87" //@"首页_点击确认支付按钮_购买成功页_点击首页按钮"
#define mainViewbtn88               @"mainViewbtn88" //@"首页_点击确认支付按钮_购买成功页_点击查看订单按钮"
#define mainViewbtn89               @"mainViewbtn89" //@"首页_点击确认支付按钮_购买成功页_获得奖励页"
#define mainViewbtn90               @"mainViewbtn90" //@"首页_点击确认支付按钮_购买成功页_获得奖励页_点击知道了按钮"
#define mainViewbtn91               @"mainViewbtn91" //@"首页_点击确认支付按钮_购买成功页_获得奖励页_点击关闭按钮"

//10.	按钮被点击次数，影院首页_小卖部：
#define mainViewbtn92               @"mainViewbtn92" //@"首页_点击小卖部"
#define mainViewbtn93               @"mainViewbtn93" //@"首页_点击卖品数量(加)"
#define mainViewbtn94               @"mainViewbtn94" //@"首页_点击卖品数量(减)"
#define mainViewbtn95               @"mainViewbtn95" //@"首页_点击去结账按钮"
#define mainViewbtn96               @"mainViewbtn96" //@"首页_点击去结账按钮_订单确认页_点击权益优惠栏"
#define mainViewbtn97               @"mainViewbtn97" //@"首页_点击去结账按钮_订单确认页_权益优惠栏_点击优惠数量(加)"
#define mainViewbtn98               @"mainViewbtn98" //@"首页_点击去结账按钮_订单确认页_权益优惠栏_点击优惠数量(减)"
#define mainViewbtn99               @"mainViewbtn99" //@"首页_点击去结账按钮_订单确认页_权益优惠栏_点击实付金额"
#define mainViewbtn100               @"mainViewbtn100" //@"首页_点击去结账按钮_订单确认页_点击手机号栏"
#define mainViewbtn101               @"mainViewbtn101" //@"首页_点击去结账按钮_订单确认页_点击查看明细按钮"
#define mainViewbtn102               @"mainViewbtn102" //@"首页_点击去结账按钮_订单确认页_点击确认订单按钮"
#define mainViewbtn103               @"mainViewbtn103" //@"首页_点击去结账按钮_支付选择页_点击微信支付"
#define mainViewbtn104               @"mainViewbtn104" //@"首页_点击去结账按钮_支付选择页_点击支付宝支付"
#define mainViewbtn105               @"mainViewbtn105" //@"首页_点击去结账按钮_支付选择页_点击Apple Pay支付"
#define mainViewbtn106               @"mainViewbtn106" //@"首页_点击去结账按钮_支付选择页_点击确认支付按钮"
#define mainViewbtn107               @"mainViewbtn107" //@"首页_点击去结账按钮_支付选择页_点击返回按钮"

//购小卖成功页
#define mainViewbtn108               @"mainViewbtn108" //@"首页_点击去结账按钮_购买成功页_点击立即领取按钮"
#define mainViewbtn109               @"mainViewbtn109" //@"首页_点击去结账按钮_购买成功页_点击首页按钮"
#define mainViewbtn110               @"mainViewbtn110" //@"首页_点击去结账按钮_购买成功页_点击查看订单按钮"
#define mainViewbtn111               @"mainViewbtn111" //@"首页_点击去结账按钮_购买成功页_获得奖励页"
#define mainViewbtn112               @"mainViewbtn112" //@"首页_点击去结账按钮_购买成功页_获得奖励页_点击知道了按钮"
#define mainViewbtn113               @"mainViewbtn113" //@"首页_点击去结账按钮_购买成功页_获得奖励页_点击关闭按钮"

//11.	按钮被点击次数，影院首页_凑热闹：
#define mainViewbtn114               @"mainViewbtn114" //@"首页_点击凑热闹"
#define mainViewbtn115               @"mainViewbtn115" //@"首页_凑热闹_点击立即参加按钮"
#define mainViewbtn116               @"mainViewbtn116" //@"首页_凑热闹_查看详情按钮"

//12.	按钮被点击次数，影院首页_影片详情：
#define mainViewbtn117               @"mainViewbtn117" //@"首页_点击影片详情"
#define mainViewbtn118               @"mainViewbtn118" //@"首页_影片详情_点击想看按钮"
#define mainViewbtn119               @"mainViewbtn119" //@"首页_影片详情_点击取消想看按钮"
//#define mainViewbtn120               @"首页_影片详情_点击评价/评分按钮"
//#define mainViewbtn121               @"首页_影片详情_点击评价/评分按钮_评价页_点击超赞"
//#define mainViewbtn122               @"首页_影片详情_点击评价/评分按钮_评价页_点击推荐"
//#define mainViewbtn123               @"首页_影片详情_点击评价/评分按钮_评价页_点击还行"
//#define mainViewbtn124               @"首页_影片详情_点击评价/评分按钮_评价页_点击呃…"
//#define mainViewbtn125               @"首页_影片详情_点击评价/评分按钮_评价页_点击烂"
//#define mainViewbtn126               @"首页_影片详情_点击评价/评分按钮_评价页_点击发布按钮"
//#define mainViewbtn127               @"首页_影片详情_点击评价/评分按钮_评价页_点击关闭按钮"
#define mainViewbtn128               @"mainViewbtn128" //@"首页_影片详情_点击详情按钮"
#define mainViewbtn129               @"mainViewbtn129" //@"首页_影片详情_点击详情按钮_详情页"
#define mainViewbtn130               @"mainViewbtn130" //@"首页_影片详情_点击详情按钮_详情页_点击预告片"
#define mainViewbtn131               @"mainViewbtn131" //@"首页_影片详情_点击详情按钮_详情页_点击剧照图"
#define mainViewbtn132               @"mainViewbtn132" //@"首页_影片详情_点击详情按钮_详情页_点击展开按钮"
#define mainViewbtn133               @"mainViewbtn133" //@"首页_影片详情_点击详情按钮_详情页_点击收起按钮"
#define mainViewbtn134               @"mainViewbtn134" //@"首页_影片详情_点击购票按钮"
#define mainViewbtn135               @"mainViewbtn135" //@"首页_影片详情_点击返回按钮"
#define mainViewbtn136               @"mainViewbtn136" //@"首页_影片详情_点击短评页"
#define mainViewbtn137               @"mainViewbtn137" //@"首页_影片详情_短评页_点击想看"
#define mainViewbtn138               @"mainViewbtn138" //@"首页_影片详情_短评页_点击已想看"
#define mainViewbtn139               @"mainViewbtn139" //@"首页_影片详情_短评页_点击写短评"
#define mainViewbtn140               @"mainViewbtn140" //@"首页_影片详情_短评页_写短评页_点击超赞"
#define mainViewbtn141               @"mainViewbtn141" //@"首页_影片详情_写短评页_点击推荐"
#define mainViewbtn142               @"mainViewbtn142" //@"首页_影片详情_写短评页_点击还行"
#define mainViewbtn143               @"mainViewbtn143" //@"首页_影片详情_写短评页_点击呃…"
#define mainViewbtn144               @"mainViewbtn144" //@"首页_影片详情_写短评页_点击烂"
#define mainViewbtn145               @"mainViewbtn145" //@"首页_影片详情_写短评页_点击发布按钮"
#define mainViewbtn146               @"mainViewbtn146" //@"首页_影片详情_写短评页_点击关闭按钮"
#define mainViewbtn147               @"mainViewbtn147" //@"首页_影片详情_短评页_点击点赞按钮"
#define mainViewbtn148               @"mainViewbtn148" //@"首页_影片详情_短评页_点击关注按钮"
#define mainViewbtn149               @"mainViewbtn149" //@"首页_影片详情_短评页_点击删除按钮"
#define mainViewbtn150               @"mainViewbtn150" //@"首页_影片详情_短评页_点击删除按钮_点击确认按钮"
#define mainViewbtn151               @"mainViewbtn151" //@"首页_影片详情_短评页_点击删除按钮_点击取消按钮"
#define mainViewbtn152               @"mainViewbtn152" //@"首页_影片详情_短评页_点击举报按钮"
#define mainViewbtn153               @"mainViewbtn153" //@"首页_影片详情_短评页_点击举报按钮_色情，淫秽或低俗内容"
#define mainViewbtn154               @"mainViewbtn154" //@"首页_影片详情_短评页_点击举报按钮_广告或垃圾信息"
#define mainViewbtn155               @"mainViewbtn155" //@"首页_影片详情_短评页_点击举报按钮_激进时政或者意识形态"
//#define mainViewbtn156               @"首页_影片详情_短评页_点击举报按钮_点击确认按钮"
#define mainViewbtn157               @"mainViewbtn157" //@"首页_影片详情_短评页_点击举报按钮_点击取消按钮"
#define mainViewbtn158               @"mainViewbtn158" //@"首页_影片详情_短评页_点击回复按钮"
#define mainViewbtn159               @"mainViewbtn159" //@"首页_影片详情_短评页_点击回复按钮_点击发送按钮"
#define mainViewbtn160               @"mainViewbtn160" //@"首页_影片详情_短评页_点击更多回复按钮"
//13.	按钮被点击次数，个人中心：
#define myCenterViewbtn1               @"myCenterViewbtn1" //@"点击个人中心"
#define myCenterViewbtn2               @"myCenterViewbtn2" //@"点击个人中心_点击个性签名"
#define myCenterViewbtn3               @"myCenterViewbtn3" //@"点击个人中心_个性签名_编辑签名页_点击确认按钮"
#define myCenterViewbtn4               @"myCenterViewbtn4" //@"点击个人中心_个性签名_编辑签名页_点击关闭按钮"
#define myCenterViewbtn5               @"myCenterViewbtn5" //@"点击个人中心_点击关注按钮"
#define myCenterViewbtn6               @"myCenterViewbtn6" //@"点击个人中心_点击关注按钮_点击互相关注按钮"
#define myCenterViewbtn7               @"myCenterViewbtn7" //@"点击个人中心_点击关注按钮_点击已关注按钮"
#define myCenterViewbtn8               @"myCenterViewbtn8" //@"点击个人中心_点击关注按钮_点击用户头像"
#define myCenterViewbtn9               @"myCenterViewbtn9" //@"点击个人中心_点击关注按钮_点击关闭按钮"
#define myCenterViewbtn10               @"myCenterViewbtn10" //@"点击个人中心_点击粉丝按钮"
#define myCenterViewbtn11               @"myCenterViewbtn11" //@"点击个人中心_点击粉丝按钮_点击互相关注按钮"
#define myCenterViewbtn12               @"myCenterViewbtn12" //@"点击个人中心_点击粉丝按钮_点击已关注按钮"
#define myCenterViewbtn13               @"myCenterViewbtn13" //@"点击个人中心_点击粉丝按钮_点击关注按钮"
#define myCenterViewbtn14               @"myCenterViewbtn14" //@"点击个人中心_点击粉丝按钮_点击用户头像"
#define myCenterViewbtn15               @"myCenterViewbtn15" //@"点击个人中心_点击粉丝按钮_点击返回按钮"
#define myCenterViewbtn16               @"myCenterViewbtn16" //@"点击个人中心_点击想看按钮"
#define myCenterViewbtn17               @"myCenterViewbtn17" //@"点击个人中心_点击想看按钮_点击影片"
#define myCenterViewbtn18               @"myCenterViewbtn18" //@"点击个人中心_点击想看按钮_点击返回按钮"
#define myCenterViewbtn19               @"myCenterViewbtn19" //@"点击个人中心_点击短评按钮"
#define myCenterViewbtn20               @"myCenterViewbtn20" //@"点击个人中心_点击短评按钮_点击影片"
#define myCenterViewbtn21               @"myCenterViewbtn21" //@"点击个人中心_点击短评按钮_点击返回按钮"
#define myCenterViewbtn22               @"myCenterViewbtn22" //@"点击个人中心_点击我的订单"
#define myCenterViewbtn23               @"myCenterViewbtn23" //@"点击个人中心_我的订单_全部"
#define myCenterViewbtn24               @"myCenterViewbtn24" //@"点击个人中心_我的订单_待付款"
#define myCenterViewbtn25               @"myCenterViewbtn25" //@"点击个人中心_我的订单_待使用"
#define myCenterViewbtn26               @"myCenterViewbtn26" //@"点击个人中心_我的订单_退款"
#define myCenterViewbtn27               @"myCenterViewbtn27" //@"点击个人中心_我的订单_点击支付按钮"
#define myCenterViewbtn28               @"myCenterViewbtn28" //@"点击个人中心_我的订单_点击删除按钮"
#define myCenterViewbtn29               @"myCenterViewbtn29" //@"点击个人中心_点击我的卡包"

#define myCenterViewbtn30               @"myCenterViewbtn30" //@"点击个人中心_我的卡包_点击会员权益"
#define myCenterViewbtn31               @"myCenterViewbtn31" //@"点击个人中心_我的卡包_会员权益_点击有效权益"
#define myCenterViewbtn32               @"myCenterViewbtn32" //@"点击个人中心_我的卡包_会员权益_有效权益_点击前往这家影院按钮"//
#define myCenterViewbtn33               @"myCenterViewbtn33" //@"点击个人中心_我的卡包_会员权益_有效权益_点击影院名称按钮（IOS）"
#define myCenterViewbtn34               @"myCenterViewbtn34" //@"点击个人中心_我的卡包_会员权益_点击失效权益"
#define myCenterViewbtn35               @"myCenterViewbtn35" //@"点击个人中心_我的卡包_会员权益_失效权益_点击再次购买按钮"
#define myCenterViewbtn36               @"myCenterViewbtn36" //@"点击个人中心_我的卡包_会员权益_失效权益_点击前往这家影院按钮"//
#define myCenterViewbtn37               @"myCenterViewbtn37" //@"点击个人中心_我的卡包_会员权益_有效权益_点击影院名称按钮（IOS）"
#define myCenterViewbtn38               @"myCenterViewbtn38" //@"点击个人中心_我的卡包_点击优惠券"
#define myCenterViewbtn39               @"myCenterViewbtn39" //@"点击个人中心_我的卡包_会员权益_点击有效优惠券"
#define myCenterViewbtn40               @"myCenterViewbtn40" //@"点击个人中心_我的卡包_会员权益_有效优惠券_点击线下券核销码"
#define myCenterViewbtn41               @"myCenterViewbtn41" //@"点击个人中心_我的卡包_会员权益_点击失效优惠券"
//#define myCenterViewbtn42               @"点击个人中心_我的卡包_点击返回按钮"//

#define myCenterViewbtn43               @"myCenterViewbtn43" //@"点击个人中心_点击激活码"
//#define myCenterViewbtn44               @"点击个人中心_激活码_点击兑换按钮"
//#define myCenterViewbtn45               @"点击个人中心_激活码_点击客服电话"
//#define myCenterViewbtn46               @"点击个人中心_激活码_点击返回按钮"
#define myCenterViewbtn47               @"myCenterViewbtn47" //@"点击个人中心_点击我的动态"
#define myCenterViewbtn55               @"myCenterViewbtn55" //@"点击个人中心_点击通知"
//--@caochao
#define myCenterViewbtn48               @"myCenterViewbtn48" //@"点击个人中心_我的动态_点击点赞按钮"
#define myCenterViewbtn49               @"myCenterViewbtn49" //@"点击个人中心_我的动态_点击评论按钮"
#define myCenterViewbtn50               @"myCenterViewbtn50" //@"点击个人中心_我的动态_点击影片信息栏"
#define myCenterViewbtn51               @"myCenterViewbtn51" //@"点击个人中心_我的动态_点击用户信息栏"
#define myCenterViewbtn52               @"myCenterViewbtn52" //@"点击个人中心_我的动态_点击活动信息栏"
#define myCenterViewbtn53               @"myCenterViewbtn53" //@"点击个人中心_我的动态_点击删除按钮"
#define myCenterViewbtn54               @"myCenterViewbtn54" //@"点击个人中心_我的动态_点击短评影片信息栏"
#define myCenterViewbtn56               @"myCenterViewbtn56" //@"点击个人中心_通知_点击社交通知"
#define myCenterViewbtn57               @"myCenterViewbtn57" //@"点击个人中心_通知_社交通知_点击用户头像/昵称"
#define myCenterViewbtn58               @"myCenterViewbtn58" //@"点击个人中心_通知_社交通知_点击用户头像/昵称"
#define myCenterViewbtn59               @"myCenterViewbtn59" //@"点击个人中心_通知_社交通知_点击动态"
#define myCenterViewbtn60               @"myCenterViewbtn60" //@"点击个人中心_通知_社交通知_点击动态回复"
#define myCenterViewbtn61               @"myCenterViewbtn61" //@"点击个人中心_通知_点击系统通知"
//--
#define myCenterViewbtn62               @"myCenterViewbtn62" //@"点击个人中心_点击设置"
#define myCenterViewbtn63               @"myCenterViewbtn63" //@"点击个人中心_设置_点击个人头像"
#define myCenterViewbtn64               @"myCenterViewbtn64" //@"点击个人中心_设置_个人头像_点击默认头像1"
#define myCenterViewbtn65               @"myCenterViewbtn65" //@"点击个人中心_设置_个人头像_点击默认头像2"
#define myCenterViewbtn66               @"myCenterViewbtn66" //@"点击个人中心_设置_个人头像_点击默认头像3"
#define myCenterViewbtn67               @"myCenterViewbtn67" //@"点击个人中心_设置_个人头像_点击默认头像4"
#define myCenterViewbtn68               @"myCenterViewbtn68" //@"点击个人中心_设置_个人头像_点击拍照"
#define myCenterViewbtn69               @"myCenterViewbtn69" //@"点击个人中心_设置_个人头像_点击从手机相册中选择"
#define myCenterViewbtn70               @"myCenterViewbtn70" //@"点击个人中心_设置_个人头像_点击保存照片"
#define myCenterViewbtn71               @"myCenterViewbtn71" //@"点击个人中心_设置_点击主页背景"
#define myCenterViewbtn75               @"myCenterViewbtn75" //@"点击个人中心_设置_点击昵称"
#define myCenterViewbtn77               @"myCenterViewbtn77" //@"点击个人中心_设置_昵称_点击保存按钮"
//#define myCenterViewbtn78               @"点击个人中心_设置_昵称_点击返回按钮"
#define myCenterViewbtn79               @"myCenterViewbtn79" //@"点击个人中心_设置_点击性别"
#define myCenterViewbtn80               @"myCenterViewbtn80" //@"点击个人中心_设置_性别_点击男"
#define myCenterViewbtn81               @"myCenterViewbtn81" //@"点击个人中心_设置_性别_点击女"
#define myCenterViewbtn84               @"myCenterViewbtn84" //@"点击个人中心_设置_点击生日"
#define myCenterViewbtn85               @"myCenterViewbtn85" //@"点击个人中心_设置_生日_点击生日日期"
#define myCenterViewbtn86               @"myCenterViewbtn86" //@"点击个人中心_设置_生日_点击确认按钮"
#define myCenterViewbtn87               @"myCenterViewbtn87" //@"点击个人中心_设置_生日_点击取消按钮"
#define myCenterViewbtn88               @"myCenterViewbtn88" //@"点击个人中心_设置_点击密码"
#define myCenterViewbtn91               @"myCenterViewbtn91" //@"点击个人中心_设置_密码_点击保存按钮"
#define myCenterViewbtn92               @"myCenterViewbtn92" //@"点击个人中心_设置_密码_点击返回按钮"
#define myCenterViewbtn93               @"myCenterViewbtn93" //@"点击个人中心_设置_点击手机号"
#define myCenterViewbtn96               @"myCenterViewbtn96" //@"点击个人中心_设置_手机号_点击获取验证码按钮"
//#define myCenterViewbtn97               @"点击个人中心_设置_手机号_点击验证码栏"
#define myCenterViewbtn98               @"myCenterViewbtn98" //@"点击个人中心_设置_手机号_点击保存按钮"
#define myCenterViewbtn99               @"myCenterViewbtn99" //@"点击个人中心_设置_手机号_点击返回按钮"
#define myCenterViewbtn100              @"myCenterViewbtn100" //@"点击个人中心_设置_点击通知设置"
//#define myCenterViewbtn101               @"点击个人中心_设置_通知设置_点击为短评点赞开启"
//#define myCenterViewbtn102               @"点击个人中心_设置_通知设置_点击为短评点赞关闭"
//#define myCenterViewbtn103               @"点击个人中心_设置_通知设置_点击添加关注的人开启"
//#define myCenterViewbtn104               @"点击个人中心_设置_通知设置_点击添加关注的人关闭"
//#define myCenterViewbtn105               @"点击个人中心_设置_通知设置_点击添加看过的影片开启"
//#define myCenterViewbtn106               @"点击个人中心_设置_通知设置_点击添加看过的影片关闭"
//#define myCenterViewbtn107               @"点击个人中心_设置_通知设置_点击添加想看的影片开启"
//#define myCenterViewbtn108               @"点击个人中心_设置_通知设置_点击添加想看的影片关闭"
//#define myCenterViewbtn109               @"点击个人中心_设置_通知设置_点击参与线上活动开启"
//#define myCenterViewbtn110               @"点击个人中心_设置_通知设置_点击参与线上活动关闭"
//#define myCenterViewbtn111               @"点击个人中心_设置_通知设置_点击确认修改"
//#define myCenterViewbtn112               @"点击个人中心_设置_通知设置_点击返回按钮"
#define myCenterViewbtn113               @"myCenterViewbtn113" //@"点击个人中心_设置_点击意见反馈"
#define myCenterViewbtn116               @"myCenterViewbtn116" //@"点击个人中心_设置_意见反馈_点击添加图片"
#define myCenterViewbtn117               @"myCenterViewbtn117" //@"点击个人中心_设置_意见反馈_点击确认按钮"
#define myCenterViewbtn118               @"myCenterViewbtn118" //@"点击个人中心_设置_意见反馈_点击返回按钮"
#define myCenterViewbtn119               @"myCenterViewbtn119" //@"点击个人中心_设置_点击关于"
#define myCenterViewbtn120               @"myCenterViewbtn120" //@"点击个人中心_设置_关于_点击检查更新"
#define myCenterViewbtn121               @"myCenterViewbtn121" //@"点击个人中心_设置_关于_检查更新_点击立即更新按钮"
#define myCenterViewbtn122               @"myCenterViewbtn122" //@"点击个人中心_设置_关于_检查更新_点击下次再说按钮"
#define myCenterViewbtn123               @"myCenterViewbtn123" //@"点击个人中心_设置_关于_检查更新_点击关闭按钮"
#define myCenterViewbtn124               @"myCenterViewbtn124" //@"点击个人中心_设置_关于_点击使用协议"
#define myCenterViewbtn125               @"myCenterViewbtn125" //@"点击个人中心_设置_关于_使用协议_点击返回按钮"
#define myCenterViewbtn126               @"myCenterViewbtn126" //@"点击个人中心_设置_关于_点击软件评分"
#define myCenterViewbtn127               @"myCenterViewbtn127" //@"点击个人中心_设置_关于_点击返回按钮"
#define myCenterViewbtn128               @"myCenterViewbtn128" //@"点击个人中心_设置_点击退出"
#define myCenterViewbtn129               @"myCenterViewbtn129" //@"点击个人中心_设置_退出_点击退出当前帐号"
#define myCenterViewbtn130               @"myCenterViewbtn130" //@"点击个人中心_设置_退出_点击取消按钮"
//14.	按钮被点击次数，通知：
#define activityViewbtn1               @"activityViewbtn1" //@"活动通知_点击查看详情按钮"
#define activityViewbtn2               @"activityViewbtn2" //@"活动通知_点击关闭按钮"
#define activityViewbtn3               @"activityViewbtn3" //@"H5通知_点击H5区域"
#define activityViewbtn4               @"activityViewbtn4" //@"H5通知_点击H5区域_打开webvivew页面"
#define activityViewbtn5               @"activityViewbtn5" //@"H5通知_点击H5区域_打开webvivew页面_点击返回按钮"
#define activityViewbtn6               @"activityViewbtn6" //@"H5通知_点击H5区域_打开webvivew页面_点击分享按钮"
#define activityViewbtn8               @"activityViewbtn8" //@"广播公告_点击广播公告栏"
#define activityViewbtn9               @"activityViewbtn9" //@"广播公告_点击关闭按钮"
//新加
#define mainViewbtn161              @"mainViewbtn161" //@"影院321倒数页_点击跳过按钮"
#define mainViewbtn162              @"mainViewbtn162" //@"影院321倒数页_点击返回按钮"
//#define loginViewbtn9               @"登录页_点击语音验证码按钮"
#define registerViewbtn8            @"registerViewbtn8" //@"注册页_点击语音验证码按钮"
#define findPwdViewbtn4             @"findPwdViewbtn4" //@"忘记密码页_点击语音验证码按钮"
#define myCenterViewbtn131          @"myCenterViewbtn131" //@"绑定手机号页_点击语音验证码按钮"
